FROM python:3.10-slim-buster


#WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
#set Environemt Variables
#Inside Container and will  remain set when the container is running
ENV FLASK_ENV=development

EXPOSE ${PORT}

#CMD
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]